// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/KwokBy/easy-ops/api"
	"github.com/KwokBy/easy-ops/api/handlers"
	"github.com/KwokBy/easy-ops/app"
	"github.com/KwokBy/easy-ops/repo"
	"github.com/KwokBy/easy-ops/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitServer Injectors from wire.go:
func InitServer() *app.Server {
	engine := app.NewGinEngine()
	db := app.InitGormMySql()
	iDemoRepo := repo.NewMysqlDemoRepo(db)
	iDemoService := service.NewDemoService(iDemoRepo)
	demoHandler := handlers.NewDemoHandler(iDemoService)
	userHandler := handlers.NewUserHandler()
	apiRouter := &api.Router{
		Demo: demoHandler,
		User: userHandler,
	}
	server := app.NewServer(engine, apiRouter)
	return server
}

// wire.go:

var router = wire.NewSet(wire.Struct(new(api.Router), "*"))
